In [58]:
import pandas as pd
import numpy as np

In [59]:
postings = pd.read_csv("postings.csv")

In [60]:
postings.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [61]:
postings.shape

(123849, 31)

In [62]:
postings.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']

In [63]:
keywords = [
    'data analyst',
    'business analyst',
    'data scientist',
    'data engineer',
    'bi analyst'
]

In [64]:
jobs = postings[
    postings['title']
    .str.lower()
    .str.contains('|'.join(keywords), na=False)
]

In [65]:
jobs.shape

(1612, 31)

In [66]:
jobs['title'].value_counts().head(20)

title
Business Analyst                             146
Data Analyst                                 137
Data Engineer                                 90
Data Scientist                                56
Senior Data Engineer                          44
Senior Business Analyst                       34
Senior Data Analyst                           25
Senior Data Scientist                         21
Online Data Analyst                           20
Technical Business Analyst                    16
Lead Data Engineer                            12
Lead Data Scientist                           11
Business Data Analyst                         10
IT Business Analyst                           10
Data Engineer II                               7
Sr. Business Analyst                           7
Sr. Data Engineer                              6
Data Scientist Lead – Telematics (Remote)      6
Junior Business Analyst                        5
Master Data Analyst                            5
Name: count, dtype: int64

In [67]:
keep_cols = [
    'job_id',
    'company_name',
    'title',
    'description',
    'location',
    'formatted_work_type',
    'remote_allowed',
    'min_salary',
    'max_salary',
    'applies'
]

In [68]:
jobs_clean = jobs[keep_cols].copy()

In [69]:
jobs_clean.head()

,job_id,company_name,title,description,location,formatted_work_type,remote_allowed,min_salary,max_salary,applies
283,3742692445,ZenithMinds Inc,Sr Data Engineer with Kafka,Data Engineer with Kafka (W2 Only)💯% Remote\nM...,"Austin, TX",Full-time,1.0,NaN,NaN,10.0
325,3780415828,CapAcuity,Technical Business Analyst,We’re actively seeking a Technical Business An...,"Albany, NY",Contract,NaN,60000.0,80000.0,NaN
360,3797449314,"Subaru Research and Development, Inc",Cloud Platform/ Big Data Engineer,About Subaru Research and Development:Do you c...,"Michigan, United States",Full-time,NaN,NaN,NaN,1.0
367,3800989742,SilverSpace Technologies Inc,Data Engineer/ETL,"Responsibilities:Develop new features, fix bug...","Hartford, CT",Contract,NaN,NaN,NaN,12.0
389,3813645405,Tenazx Inc,Data Analyst,Job Title: Data AnalystDuration: ContractLocat...,"Queens, NY",Contract,NaN,NaN,NaN,NaN

In [70]:
jobs_clean.rename(
    columns={
        'company_name':'company',
        'title':'job_title',
        'description':'job_description',
        'formatted_work_type':'job_type'
    },
    inplace=True
)

In [71]:
jobs_clean.columns

Index(['job_id', 'company', 'job_title', 'job_description', 'location',
       'job_type', 'remote_allowed', 'min_salary', 'max_salary', 'applies'],
      dtype='object')

In [72]:
jobs_clean['avg_salary'] = (
    jobs_clean['min_salary'] +
    jobs_clean['max_salary']
)/2

In [73]:
jobs_clean[
['min_salary','max_salary','avg_salary']
].head()

     min_salary  max_salary  avg_salary
283         NaN         NaN         NaN
325     60000.0     80000.0     70000.0
360         NaN         NaN         NaN
367         NaN         NaN         NaN
389         NaN         NaN         NaN

In [74]:
jobs_clean.duplicated().sum()

np.int64(0)

In [77]:
jobs_clean.isnull().sum()

job_id                0
company              18
job_title             0
job_description       0
location              0
job_type              0
remote_allowed     1136
min_salary         1150
max_salary         1150
applies             680
avg_salary         1150
dtype: int64

In [78]:
jobs_clean = jobs_clean.dropna(
    subset=['job_description']
)

In [79]:
jobs_clean['company'] = jobs_clean[
    'company'
].fillna('Unknown')

In [80]:
jobs_clean['location'] = jobs_clean[
    'location'
].fillna('Unknown')

In [81]:
jobs_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1612 entries, 283 to 123727
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           1612 non-null   int64
 1   company          1612 non-null   object
 2   job_title        1612 non-null   object
 3   job_description  1612 non-null   object
 4   location         1612 non-null   object
 5   job_type         1612 non-null   object
 6   remote_allowed   476 non-null    float64
 7   min_salary       462 non-null    float64
 8   max_salary       462 non-null    float64
 9   applies          932 non-null    float64
 10  avg_salary       462 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 151.1+ KB

In [82]:
jobs_clean.to_csv(
    "cleaned_jobs.csv",
    index=False
)