In [1]:
import pandas as pd

jobs_clean = pd.read_csv(
    "cleaned_jobs.csv"
)

In [2]:
skills_dictionary = [
    'sql',
    'excel',
    'python',
    'power bi',
    'tableau',
    'aws',
    'azure',
    'spark',
    'snowflake',
    'etl',
    'statistics',
    'machine learning',
    'data visualization'
]

In [3]:
def extract_skills(description):

    description = str(description).lower()

    found_skills = []

    for skill in skills_dictionary:

        if skill in description:

            found_skills.append(skill)

    return found_skills

In [4]:
jobs_clean['technical_skills'] = (
    jobs_clean['job_description']
    .apply(extract_skills)
)

In [5]:
jobs_clean[
['job_title','technical_skills']
].head(10)

,job_title,technical_skills
0,Sr Data Engineer with Kafka,"[sql, python, aws, snowflake, etl]"
1,Technical Business Analyst,[sql]
2,Cloud Platform/ Big Data Engineer,"[python, aws, azure]"
3,Data Engineer/ETL,"[sql, aws]"
4,Data Analyst,"[sql, excel, python, statistics, data visualiz..."
5,Senior Data Engineer/Analyst - Full Time,[]
6,Junior Business Analyst,[excel]
7,Technical Business Analyst Local to Des Moines...,[]
8,eCommerce Data Analyst,[excel]
9,Azure Data Engineer (Full time),"[sql, python, aws, azure, spark, etl]"

In [6]:
jobs_clean['technical_skills_text'] = (
    jobs_clean['technical_skills']
    .apply(lambda x: ', '.join(x))
)

In [7]:
from collections import Counter

In [8]:
all_skills = []

for skills in jobs_clean[
    'technical_skills'
]:
    all_skills.extend(skills)

In [9]:
skill_counts = Counter(
    all_skills
)

In [10]:
skill_demand = pd.DataFrame(
    skill_counts.items(),
    columns=[
        'skill',
        'count'
    ]
)

In [11]:
skill_demand = skill_demand.sort_values(
    by='count',
    ascending=False
)

In [12]:
skill_demand

                 skill  count
0                  sql    866
6                excel    864
1               python    682
2                  aws    436
12    machine learning    319
7           statistics    295
9                spark    262
5                azure    251
4                  etl    229
11             tableau    211
8   data visualization    187
10            power bi    166
3            snowflake    144

In [13]:
skill_demand.to_csv(
    "skill_demand.csv",
    index=False
)

In [14]:
jobs_clean.to_csv(
    "cleaned_jobs_with_skills.csv",
    index=False
)

In [17]:
import pandas as pd

df = pd.read_csv("cleaned_jobs_with_skills.csv")

df.shape

(1612, 13)

In [18]:
df.columns

Index(['job_id', 'company', 'job_title', 'job_description', 'location',
       'job_type', 'remote_allowed', 'min_salary', 'max_salary', 'applies',
       'avg_salary', 'technical_skills', 'technical_skills_text'],
      dtype='object')

In [19]:
df.to_csv("final_jobs_for_sql.csv", index=False)